apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: cp-pkg-platform-ref-azure
spec:
  ignoreCrossplaneConstraints: false
  package: registry.upbound.io/nate-organization/cp-pkg-platform-ref-azure:v0.0.2
  packagePullPolicy: Always
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false
  
